services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=runnerz'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=kevin'
    ports:
      - '5432:5432'